// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/PsichiX/JustIDS/message/playerInfo.proto

package com.PsichiX.JustIDS.message;

public final class PlayerInformation {
  private PlayerInformation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.PsichiX.JustIDS.PlayerState}
   */
  public enum PlayerState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>WAITING = 0;</code>
     */
    WAITING(0, 0),
    /**
     * <code>IN_GAME = 1;</code>
     */
    IN_GAME(1, 1),
    /**
     * <code>PLAYING = 2;</code>
     */
    PLAYING(2, 2),
    /**
     * <code>OBSERVER = 3;</code>
     */
    OBSERVER(3, 3),
    /**
     * <code>WON = 4;</code>
     */
    WON(4, 4),
    /**
     * <code>LOST = 5;</code>
     */
    LOST(5, 5),
    /**
     * <code>GAME_FINISHED = 6;</code>
     */
    GAME_FINISHED(6, 6),
    ;

    /**
     * <code>WAITING = 0;</code>
     */
    public static final int WAITING_VALUE = 0;
    /**
     * <code>IN_GAME = 1;</code>
     */
    public static final int IN_GAME_VALUE = 1;
    /**
     * <code>PLAYING = 2;</code>
     */
    public static final int PLAYING_VALUE = 2;
    /**
     * <code>OBSERVER = 3;</code>
     */
    public static final int OBSERVER_VALUE = 3;
    /**
     * <code>WON = 4;</code>
     */
    public static final int WON_VALUE = 4;
    /**
     * <code>LOST = 5;</code>
     */
    public static final int LOST_VALUE = 5;
    /**
     * <code>GAME_FINISHED = 6;</code>
     */
    public static final int GAME_FINISHED_VALUE = 6;


    public final int getNumber() { return value; }

    public static PlayerState valueOf(int value) {
      switch (value) {
        case 0: return WAITING;
        case 1: return IN_GAME;
        case 2: return PLAYING;
        case 3: return OBSERVER;
        case 4: return WON;
        case 5: return LOST;
        case 6: return GAME_FINISHED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PlayerState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<PlayerState>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PlayerState>() {
            public PlayerState findValueByNumber(int number) {
              return PlayerState.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.PsichiX.JustIDS.message.PlayerInformation.getDescriptor().getEnumTypes().get(0);
    }

    private static final PlayerState[] VALUES = values();

    public static PlayerState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private PlayerState(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.PsichiX.JustIDS.PlayerState)
  }

  public interface PlayerOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string id = 1;
    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    // required string name = 2;
    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // required double life_points = 3;
    /**
     * <code>required double life_points = 3;</code>
     */
    boolean hasLifePoints();
    /**
     * <code>required double life_points = 3;</code>
     */
    double getLifePoints();

    // optional string ip_address = 4;
    /**
     * <code>optional string ip_address = 4;</code>
     */
    boolean hasIpAddress();
    /**
     * <code>optional string ip_address = 4;</code>
     */
    java.lang.String getIpAddress();
    /**
     * <code>optional string ip_address = 4;</code>
     */
    com.google.protobuf.ByteString
        getIpAddressBytes();

    // required .com.PsichiX.JustIDS.PlayerState state = 6;
    /**
     * <code>required .com.PsichiX.JustIDS.PlayerState state = 6;</code>
     */
    boolean hasState();
    /**
     * <code>required .com.PsichiX.JustIDS.PlayerState state = 6;</code>
     */
    com.PsichiX.JustIDS.message.PlayerInformation.PlayerState getState();
  }
  /**
   * Protobuf type {@code com.PsichiX.JustIDS.Player}
   */
  public static final class Player extends
      com.google.protobuf.GeneratedMessage
      implements PlayerOrBuilder {
    // Use Player.newBuilder() to construct.
    private Player(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Player(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Player defaultInstance;
    public static Player getDefaultInstance() {
      return defaultInstance;
    }

    public Player getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Player(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              lifePoints_ = input.readDouble();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              ipAddress_ = input.readBytes();
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
              com.PsichiX.JustIDS.message.PlayerInformation.PlayerState value = com.PsichiX.JustIDS.message.PlayerInformation.PlayerState.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                state_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.PsichiX.JustIDS.message.PlayerInformation.internal_static_com_PsichiX_JustIDS_Player_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.PsichiX.JustIDS.message.PlayerInformation.internal_static_com_PsichiX_JustIDS_Player_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.PsichiX.JustIDS.message.PlayerInformation.Player.class, com.PsichiX.JustIDS.message.PlayerInformation.Player.Builder.class);
    }

    public static com.google.protobuf.Parser<Player> PARSER =
        new com.google.protobuf.AbstractParser<Player>() {
      public Player parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Player(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Player> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required double life_points = 3;
    public static final int LIFE_POINTS_FIELD_NUMBER = 3;
    private double lifePoints_;
    /**
     * <code>required double life_points = 3;</code>
     */
    public boolean hasLifePoints() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double life_points = 3;</code>
     */
    public double getLifePoints() {
      return lifePoints_;
    }

    // optional string ip_address = 4;
    public static final int IP_ADDRESS_FIELD_NUMBER = 4;
    private java.lang.Object ipAddress_;
    /**
     * <code>optional string ip_address = 4;</code>
     */
    public boolean hasIpAddress() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string ip_address = 4;</code>
     */
    public java.lang.String getIpAddress() {
      java.lang.Object ref = ipAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ipAddress_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ip_address = 4;</code>
     */
    public com.google.protobuf.ByteString
        getIpAddressBytes() {
      java.lang.Object ref = ipAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ipAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .com.PsichiX.JustIDS.PlayerState state = 6;
    public static final int STATE_FIELD_NUMBER = 6;
    private com.PsichiX.JustIDS.message.PlayerInformation.PlayerState state_;
    /**
     * <code>required .com.PsichiX.JustIDS.PlayerState state = 6;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required .com.PsichiX.JustIDS.PlayerState state = 6;</code>
     */
    public com.PsichiX.JustIDS.message.PlayerInformation.PlayerState getState() {
      return state_;
    }

    private void initFields() {
      id_ = "";
      name_ = "";
      lifePoints_ = 0D;
      ipAddress_ = "";
      state_ = com.PsichiX.JustIDS.message.PlayerInformation.PlayerState.WAITING;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLifePoints()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, lifePoints_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getIpAddressBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(6, state_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, lifePoints_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getIpAddressBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, state_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.PsichiX.JustIDS.message.PlayerInformation.Player parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.PsichiX.JustIDS.message.PlayerInformation.Player parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.PsichiX.JustIDS.message.PlayerInformation.Player parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.PsichiX.JustIDS.message.PlayerInformation.Player parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.PsichiX.JustIDS.message.PlayerInformation.Player parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.PsichiX.JustIDS.message.PlayerInformation.Player parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.PsichiX.JustIDS.message.PlayerInformation.Player parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.PsichiX.JustIDS.message.PlayerInformation.Player parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.PsichiX.JustIDS.message.PlayerInformation.Player parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.PsichiX.JustIDS.message.PlayerInformation.Player parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.PsichiX.JustIDS.message.PlayerInformation.Player prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.PsichiX.JustIDS.Player}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.PsichiX.JustIDS.message.PlayerInformation.PlayerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.PsichiX.JustIDS.message.PlayerInformation.internal_static_com_PsichiX_JustIDS_Player_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.PsichiX.JustIDS.message.PlayerInformation.internal_static_com_PsichiX_JustIDS_Player_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.PsichiX.JustIDS.message.PlayerInformation.Player.class, com.PsichiX.JustIDS.message.PlayerInformation.Player.Builder.class);
      }

      // Construct using com.PsichiX.JustIDS.message.PlayerInformation.Player.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        lifePoints_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        ipAddress_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        state_ = com.PsichiX.JustIDS.message.PlayerInformation.PlayerState.WAITING;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.PsichiX.JustIDS.message.PlayerInformation.internal_static_com_PsichiX_JustIDS_Player_descriptor;
      }

      public com.PsichiX.JustIDS.message.PlayerInformation.Player getDefaultInstanceForType() {
        return com.PsichiX.JustIDS.message.PlayerInformation.Player.getDefaultInstance();
      }

      public com.PsichiX.JustIDS.message.PlayerInformation.Player build() {
        com.PsichiX.JustIDS.message.PlayerInformation.Player result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.PsichiX.JustIDS.message.PlayerInformation.Player buildPartial() {
        com.PsichiX.JustIDS.message.PlayerInformation.Player result = new com.PsichiX.JustIDS.message.PlayerInformation.Player(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.lifePoints_ = lifePoints_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.ipAddress_ = ipAddress_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.state_ = state_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.PsichiX.JustIDS.message.PlayerInformation.Player) {
          return mergeFrom((com.PsichiX.JustIDS.message.PlayerInformation.Player)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.PsichiX.JustIDS.message.PlayerInformation.Player other) {
        if (other == com.PsichiX.JustIDS.message.PlayerInformation.Player.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasLifePoints()) {
          setLifePoints(other.getLifePoints());
        }
        if (other.hasIpAddress()) {
          bitField0_ |= 0x00000008;
          ipAddress_ = other.ipAddress_;
          onChanged();
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (!hasLifePoints()) {
          
          return false;
        }
        if (!hasState()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.PsichiX.JustIDS.message.PlayerInformation.Player parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.PsichiX.JustIDS.message.PlayerInformation.Player) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string id = 1;
      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      // required string name = 2;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // required double life_points = 3;
      private double lifePoints_ ;
      /**
       * <code>required double life_points = 3;</code>
       */
      public boolean hasLifePoints() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double life_points = 3;</code>
       */
      public double getLifePoints() {
        return lifePoints_;
      }
      /**
       * <code>required double life_points = 3;</code>
       */
      public Builder setLifePoints(double value) {
        bitField0_ |= 0x00000004;
        lifePoints_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double life_points = 3;</code>
       */
      public Builder clearLifePoints() {
        bitField0_ = (bitField0_ & ~0x00000004);
        lifePoints_ = 0D;
        onChanged();
        return this;
      }

      // optional string ip_address = 4;
      private java.lang.Object ipAddress_ = "";
      /**
       * <code>optional string ip_address = 4;</code>
       */
      public boolean hasIpAddress() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string ip_address = 4;</code>
       */
      public java.lang.String getIpAddress() {
        java.lang.Object ref = ipAddress_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          ipAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ip_address = 4;</code>
       */
      public com.google.protobuf.ByteString
          getIpAddressBytes() {
        java.lang.Object ref = ipAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ipAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ip_address = 4;</code>
       */
      public Builder setIpAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        ipAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip_address = 4;</code>
       */
      public Builder clearIpAddress() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ipAddress_ = getDefaultInstance().getIpAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip_address = 4;</code>
       */
      public Builder setIpAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        ipAddress_ = value;
        onChanged();
        return this;
      }

      // required .com.PsichiX.JustIDS.PlayerState state = 6;
      private com.PsichiX.JustIDS.message.PlayerInformation.PlayerState state_ = com.PsichiX.JustIDS.message.PlayerInformation.PlayerState.WAITING;
      /**
       * <code>required .com.PsichiX.JustIDS.PlayerState state = 6;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required .com.PsichiX.JustIDS.PlayerState state = 6;</code>
       */
      public com.PsichiX.JustIDS.message.PlayerInformation.PlayerState getState() {
        return state_;
      }
      /**
       * <code>required .com.PsichiX.JustIDS.PlayerState state = 6;</code>
       */
      public Builder setState(com.PsichiX.JustIDS.message.PlayerInformation.PlayerState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.PsichiX.JustIDS.PlayerState state = 6;</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000010);
        state_ = com.PsichiX.JustIDS.message.PlayerInformation.PlayerState.WAITING;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.PsichiX.JustIDS.Player)
    }

    static {
      defaultInstance = new Player(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.PsichiX.JustIDS.Player)
  }

  public interface PlayerBroadcastInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.PsichiX.JustIDS.PlayerBroadcastInfo.BroadcastType type = 1;
    /**
     * <code>required .com.PsichiX.JustIDS.PlayerBroadcastInfo.BroadcastType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .com.PsichiX.JustIDS.PlayerBroadcastInfo.BroadcastType type = 1;</code>
     */
    com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo.BroadcastType getType();

    // required .com.PsichiX.JustIDS.Player my_player = 2;
    /**
     * <code>required .com.PsichiX.JustIDS.Player my_player = 2;</code>
     */
    boolean hasMyPlayer();
    /**
     * <code>required .com.PsichiX.JustIDS.Player my_player = 2;</code>
     */
    com.PsichiX.JustIDS.message.PlayerInformation.Player getMyPlayer();
    /**
     * <code>required .com.PsichiX.JustIDS.Player my_player = 2;</code>
     */
    com.PsichiX.JustIDS.message.PlayerInformation.PlayerOrBuilder getMyPlayerOrBuilder();

    // optional double attack_strength = 3;
    /**
     * <code>optional double attack_strength = 3;</code>
     *
     * <pre>
     * Only if type = ATTACK 
     * </pre>
     */
    boolean hasAttackStrength();
    /**
     * <code>optional double attack_strength = 3;</code>
     *
     * <pre>
     * Only if type = ATTACK 
     * </pre>
     */
    double getAttackStrength();

    // repeated .com.PsichiX.JustIDS.Player all_players = 4;
    /**
     * <code>repeated .com.PsichiX.JustIDS.Player all_players = 4;</code>
     *
     * <pre>
     * Only if type = GAME_INFO
     * </pre>
     */
    java.util.List<com.PsichiX.JustIDS.message.PlayerInformation.Player> 
        getAllPlayersList();
    /**
     * <code>repeated .com.PsichiX.JustIDS.Player all_players = 4;</code>
     *
     * <pre>
     * Only if type = GAME_INFO
     * </pre>
     */
    com.PsichiX.JustIDS.message.PlayerInformation.Player getAllPlayers(int index);
    /**
     * <code>repeated .com.PsichiX.JustIDS.Player all_players = 4;</code>
     *
     * <pre>
     * Only if type = GAME_INFO
     * </pre>
     */
    int getAllPlayersCount();
    /**
     * <code>repeated .com.PsichiX.JustIDS.Player all_players = 4;</code>
     *
     * <pre>
     * Only if type = GAME_INFO
     * </pre>
     */
    java.util.List<? extends com.PsichiX.JustIDS.message.PlayerInformation.PlayerOrBuilder> 
        getAllPlayersOrBuilderList();
    /**
     * <code>repeated .com.PsichiX.JustIDS.Player all_players = 4;</code>
     *
     * <pre>
     * Only if type = GAME_INFO
     * </pre>
     */
    com.PsichiX.JustIDS.message.PlayerInformation.PlayerOrBuilder getAllPlayersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.PsichiX.JustIDS.PlayerBroadcastInfo}
   */
  public static final class PlayerBroadcastInfo extends
      com.google.protobuf.GeneratedMessage
      implements PlayerBroadcastInfoOrBuilder {
    // Use PlayerBroadcastInfo.newBuilder() to construct.
    private PlayerBroadcastInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PlayerBroadcastInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PlayerBroadcastInfo defaultInstance;
    public static PlayerBroadcastInfo getDefaultInstance() {
      return defaultInstance;
    }

    public PlayerBroadcastInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerBroadcastInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo.BroadcastType value = com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo.BroadcastType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              com.PsichiX.JustIDS.message.PlayerInformation.Player.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = myPlayer_.toBuilder();
              }
              myPlayer_ = input.readMessage(com.PsichiX.JustIDS.message.PlayerInformation.Player.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(myPlayer_);
                myPlayer_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              attackStrength_ = input.readDouble();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                allPlayers_ = new java.util.ArrayList<com.PsichiX.JustIDS.message.PlayerInformation.Player>();
                mutable_bitField0_ |= 0x00000008;
              }
              allPlayers_.add(input.readMessage(com.PsichiX.JustIDS.message.PlayerInformation.Player.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          allPlayers_ = java.util.Collections.unmodifiableList(allPlayers_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.PsichiX.JustIDS.message.PlayerInformation.internal_static_com_PsichiX_JustIDS_PlayerBroadcastInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.PsichiX.JustIDS.message.PlayerInformation.internal_static_com_PsichiX_JustIDS_PlayerBroadcastInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo.class, com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<PlayerBroadcastInfo> PARSER =
        new com.google.protobuf.AbstractParser<PlayerBroadcastInfo>() {
      public PlayerBroadcastInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerBroadcastInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerBroadcastInfo> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.PsichiX.JustIDS.PlayerBroadcastInfo.BroadcastType}
     */
    public enum BroadcastType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>STATE = 0;</code>
       */
      STATE(0, 0),
      /**
       * <code>ATTACK = 1;</code>
       */
      ATTACK(1, 1),
      ;

      /**
       * <code>STATE = 0;</code>
       */
      public static final int STATE_VALUE = 0;
      /**
       * <code>ATTACK = 1;</code>
       */
      public static final int ATTACK_VALUE = 1;


      public final int getNumber() { return value; }

      public static BroadcastType valueOf(int value) {
        switch (value) {
          case 0: return STATE;
          case 1: return ATTACK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<BroadcastType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<BroadcastType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<BroadcastType>() {
              public BroadcastType findValueByNumber(int number) {
                return BroadcastType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo.getDescriptor().getEnumTypes().get(0);
      }

      private static final BroadcastType[] VALUES = values();

      public static BroadcastType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private BroadcastType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.PsichiX.JustIDS.PlayerBroadcastInfo.BroadcastType)
    }

    private int bitField0_;
    // required .com.PsichiX.JustIDS.PlayerBroadcastInfo.BroadcastType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo.BroadcastType type_;
    /**
     * <code>required .com.PsichiX.JustIDS.PlayerBroadcastInfo.BroadcastType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.PsichiX.JustIDS.PlayerBroadcastInfo.BroadcastType type = 1;</code>
     */
    public com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo.BroadcastType getType() {
      return type_;
    }

    // required .com.PsichiX.JustIDS.Player my_player = 2;
    public static final int MY_PLAYER_FIELD_NUMBER = 2;
    private com.PsichiX.JustIDS.message.PlayerInformation.Player myPlayer_;
    /**
     * <code>required .com.PsichiX.JustIDS.Player my_player = 2;</code>
     */
    public boolean hasMyPlayer() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .com.PsichiX.JustIDS.Player my_player = 2;</code>
     */
    public com.PsichiX.JustIDS.message.PlayerInformation.Player getMyPlayer() {
      return myPlayer_;
    }
    /**
     * <code>required .com.PsichiX.JustIDS.Player my_player = 2;</code>
     */
    public com.PsichiX.JustIDS.message.PlayerInformation.PlayerOrBuilder getMyPlayerOrBuilder() {
      return myPlayer_;
    }

    // optional double attack_strength = 3;
    public static final int ATTACK_STRENGTH_FIELD_NUMBER = 3;
    private double attackStrength_;
    /**
     * <code>optional double attack_strength = 3;</code>
     *
     * <pre>
     * Only if type = ATTACK 
     * </pre>
     */
    public boolean hasAttackStrength() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional double attack_strength = 3;</code>
     *
     * <pre>
     * Only if type = ATTACK 
     * </pre>
     */
    public double getAttackStrength() {
      return attackStrength_;
    }

    // repeated .com.PsichiX.JustIDS.Player all_players = 4;
    public static final int ALL_PLAYERS_FIELD_NUMBER = 4;
    private java.util.List<com.PsichiX.JustIDS.message.PlayerInformation.Player> allPlayers_;
    /**
     * <code>repeated .com.PsichiX.JustIDS.Player all_players = 4;</code>
     *
     * <pre>
     * Only if type = GAME_INFO
     * </pre>
     */
    public java.util.List<com.PsichiX.JustIDS.message.PlayerInformation.Player> getAllPlayersList() {
      return allPlayers_;
    }
    /**
     * <code>repeated .com.PsichiX.JustIDS.Player all_players = 4;</code>
     *
     * <pre>
     * Only if type = GAME_INFO
     * </pre>
     */
    public java.util.List<? extends com.PsichiX.JustIDS.message.PlayerInformation.PlayerOrBuilder> 
        getAllPlayersOrBuilderList() {
      return allPlayers_;
    }
    /**
     * <code>repeated .com.PsichiX.JustIDS.Player all_players = 4;</code>
     *
     * <pre>
     * Only if type = GAME_INFO
     * </pre>
     */
    public int getAllPlayersCount() {
      return allPlayers_.size();
    }
    /**
     * <code>repeated .com.PsichiX.JustIDS.Player all_players = 4;</code>
     *
     * <pre>
     * Only if type = GAME_INFO
     * </pre>
     */
    public com.PsichiX.JustIDS.message.PlayerInformation.Player getAllPlayers(int index) {
      return allPlayers_.get(index);
    }
    /**
     * <code>repeated .com.PsichiX.JustIDS.Player all_players = 4;</code>
     *
     * <pre>
     * Only if type = GAME_INFO
     * </pre>
     */
    public com.PsichiX.JustIDS.message.PlayerInformation.PlayerOrBuilder getAllPlayersOrBuilder(
        int index) {
      return allPlayers_.get(index);
    }

    private void initFields() {
      type_ = com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo.BroadcastType.STATE;
      myPlayer_ = com.PsichiX.JustIDS.message.PlayerInformation.Player.getDefaultInstance();
      attackStrength_ = 0D;
      allPlayers_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMyPlayer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getMyPlayer().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getAllPlayersCount(); i++) {
        if (!getAllPlayers(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, myPlayer_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, attackStrength_);
      }
      for (int i = 0; i < allPlayers_.size(); i++) {
        output.writeMessage(4, allPlayers_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, myPlayer_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, attackStrength_);
      }
      for (int i = 0; i < allPlayers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, allPlayers_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.PsichiX.JustIDS.PlayerBroadcastInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.PsichiX.JustIDS.message.PlayerInformation.internal_static_com_PsichiX_JustIDS_PlayerBroadcastInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.PsichiX.JustIDS.message.PlayerInformation.internal_static_com_PsichiX_JustIDS_PlayerBroadcastInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo.class, com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo.Builder.class);
      }

      // Construct using com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMyPlayerFieldBuilder();
          getAllPlayersFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo.BroadcastType.STATE;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (myPlayerBuilder_ == null) {
          myPlayer_ = com.PsichiX.JustIDS.message.PlayerInformation.Player.getDefaultInstance();
        } else {
          myPlayerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        attackStrength_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (allPlayersBuilder_ == null) {
          allPlayers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          allPlayersBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.PsichiX.JustIDS.message.PlayerInformation.internal_static_com_PsichiX_JustIDS_PlayerBroadcastInfo_descriptor;
      }

      public com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo getDefaultInstanceForType() {
        return com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo.getDefaultInstance();
      }

      public com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo build() {
        com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo buildPartial() {
        com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo result = new com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (myPlayerBuilder_ == null) {
          result.myPlayer_ = myPlayer_;
        } else {
          result.myPlayer_ = myPlayerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.attackStrength_ = attackStrength_;
        if (allPlayersBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            allPlayers_ = java.util.Collections.unmodifiableList(allPlayers_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.allPlayers_ = allPlayers_;
        } else {
          result.allPlayers_ = allPlayersBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo) {
          return mergeFrom((com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo other) {
        if (other == com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasMyPlayer()) {
          mergeMyPlayer(other.getMyPlayer());
        }
        if (other.hasAttackStrength()) {
          setAttackStrength(other.getAttackStrength());
        }
        if (allPlayersBuilder_ == null) {
          if (!other.allPlayers_.isEmpty()) {
            if (allPlayers_.isEmpty()) {
              allPlayers_ = other.allPlayers_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureAllPlayersIsMutable();
              allPlayers_.addAll(other.allPlayers_);
            }
            onChanged();
          }
        } else {
          if (!other.allPlayers_.isEmpty()) {
            if (allPlayersBuilder_.isEmpty()) {
              allPlayersBuilder_.dispose();
              allPlayersBuilder_ = null;
              allPlayers_ = other.allPlayers_;
              bitField0_ = (bitField0_ & ~0x00000008);
              allPlayersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAllPlayersFieldBuilder() : null;
            } else {
              allPlayersBuilder_.addAllMessages(other.allPlayers_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasMyPlayer()) {
          
          return false;
        }
        if (!getMyPlayer().isInitialized()) {
          
          return false;
        }
        for (int i = 0; i < getAllPlayersCount(); i++) {
          if (!getAllPlayers(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.PsichiX.JustIDS.PlayerBroadcastInfo.BroadcastType type = 1;
      private com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo.BroadcastType type_ = com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo.BroadcastType.STATE;
      /**
       * <code>required .com.PsichiX.JustIDS.PlayerBroadcastInfo.BroadcastType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.PsichiX.JustIDS.PlayerBroadcastInfo.BroadcastType type = 1;</code>
       */
      public com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo.BroadcastType getType() {
        return type_;
      }
      /**
       * <code>required .com.PsichiX.JustIDS.PlayerBroadcastInfo.BroadcastType type = 1;</code>
       */
      public Builder setType(com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo.BroadcastType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.PsichiX.JustIDS.PlayerBroadcastInfo.BroadcastType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.PsichiX.JustIDS.message.PlayerInformation.PlayerBroadcastInfo.BroadcastType.STATE;
        onChanged();
        return this;
      }

      // required .com.PsichiX.JustIDS.Player my_player = 2;
      private com.PsichiX.JustIDS.message.PlayerInformation.Player myPlayer_ = com.PsichiX.JustIDS.message.PlayerInformation.Player.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.PsichiX.JustIDS.message.PlayerInformation.Player, com.PsichiX.JustIDS.message.PlayerInformation.Player.Builder, com.PsichiX.JustIDS.message.PlayerInformation.PlayerOrBuilder> myPlayerBuilder_;
      /**
       * <code>required .com.PsichiX.JustIDS.Player my_player = 2;</code>
       */
      public boolean hasMyPlayer() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .com.PsichiX.JustIDS.Player my_player = 2;</code>
       */
      public com.PsichiX.JustIDS.message.PlayerInformation.Player getMyPlayer() {
        if (myPlayerBuilder_ == null) {
          return myPlayer_;
        } else {
          return myPlayerBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.PsichiX.JustIDS.Player my_player = 2;</code>
       */
      public Builder setMyPlayer(com.PsichiX.JustIDS.message.PlayerInformation.Player value) {
        if (myPlayerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          myPlayer_ = value;
          onChanged();
        } else {
          myPlayerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .com.PsichiX.JustIDS.Player my_player = 2;</code>
       */
      public Builder setMyPlayer(
          com.PsichiX.JustIDS.message.PlayerInformation.Player.Builder builderForValue) {
        if (myPlayerBuilder_ == null) {
          myPlayer_ = builderForValue.build();
          onChanged();
        } else {
          myPlayerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .com.PsichiX.JustIDS.Player my_player = 2;</code>
       */
      public Builder mergeMyPlayer(com.PsichiX.JustIDS.message.PlayerInformation.Player value) {
        if (myPlayerBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              myPlayer_ != com.PsichiX.JustIDS.message.PlayerInformation.Player.getDefaultInstance()) {
            myPlayer_ =
              com.PsichiX.JustIDS.message.PlayerInformation.Player.newBuilder(myPlayer_).mergeFrom(value).buildPartial();
          } else {
            myPlayer_ = value;
          }
          onChanged();
        } else {
          myPlayerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .com.PsichiX.JustIDS.Player my_player = 2;</code>
       */
      public Builder clearMyPlayer() {
        if (myPlayerBuilder_ == null) {
          myPlayer_ = com.PsichiX.JustIDS.message.PlayerInformation.Player.getDefaultInstance();
          onChanged();
        } else {
          myPlayerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .com.PsichiX.JustIDS.Player my_player = 2;</code>
       */
      public com.PsichiX.JustIDS.message.PlayerInformation.Player.Builder getMyPlayerBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getMyPlayerFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.PsichiX.JustIDS.Player my_player = 2;</code>
       */
      public com.PsichiX.JustIDS.message.PlayerInformation.PlayerOrBuilder getMyPlayerOrBuilder() {
        if (myPlayerBuilder_ != null) {
          return myPlayerBuilder_.getMessageOrBuilder();
        } else {
          return myPlayer_;
        }
      }
      /**
       * <code>required .com.PsichiX.JustIDS.Player my_player = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.PsichiX.JustIDS.message.PlayerInformation.Player, com.PsichiX.JustIDS.message.PlayerInformation.Player.Builder, com.PsichiX.JustIDS.message.PlayerInformation.PlayerOrBuilder> 
          getMyPlayerFieldBuilder() {
        if (myPlayerBuilder_ == null) {
          myPlayerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.PsichiX.JustIDS.message.PlayerInformation.Player, com.PsichiX.JustIDS.message.PlayerInformation.Player.Builder, com.PsichiX.JustIDS.message.PlayerInformation.PlayerOrBuilder>(
                  myPlayer_,
                  getParentForChildren(),
                  isClean());
          myPlayer_ = null;
        }
        return myPlayerBuilder_;
      }

      // optional double attack_strength = 3;
      private double attackStrength_ ;
      /**
       * <code>optional double attack_strength = 3;</code>
       *
       * <pre>
       * Only if type = ATTACK 
       * </pre>
       */
      public boolean hasAttackStrength() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional double attack_strength = 3;</code>
       *
       * <pre>
       * Only if type = ATTACK 
       * </pre>
       */
      public double getAttackStrength() {
        return attackStrength_;
      }
      /**
       * <code>optional double attack_strength = 3;</code>
       *
       * <pre>
       * Only if type = ATTACK 
       * </pre>
       */
      public Builder setAttackStrength(double value) {
        bitField0_ |= 0x00000004;
        attackStrength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double attack_strength = 3;</code>
       *
       * <pre>
       * Only if type = ATTACK 
       * </pre>
       */
      public Builder clearAttackStrength() {
        bitField0_ = (bitField0_ & ~0x00000004);
        attackStrength_ = 0D;
        onChanged();
        return this;
      }

      // repeated .com.PsichiX.JustIDS.Player all_players = 4;
      private java.util.List<com.PsichiX.JustIDS.message.PlayerInformation.Player> allPlayers_ =
        java.util.Collections.emptyList();
      private void ensureAllPlayersIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          allPlayers_ = new java.util.ArrayList<com.PsichiX.JustIDS.message.PlayerInformation.Player>(allPlayers_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.PsichiX.JustIDS.message.PlayerInformation.Player, com.PsichiX.JustIDS.message.PlayerInformation.Player.Builder, com.PsichiX.JustIDS.message.PlayerInformation.PlayerOrBuilder> allPlayersBuilder_;

      /**
       * <code>repeated .com.PsichiX.JustIDS.Player all_players = 4;</code>
       *
       * <pre>
       * Only if type = GAME_INFO
       * </pre>
       */
      public java.util.List<com.PsichiX.JustIDS.message.PlayerInformation.Player> getAllPlayersList() {
        if (allPlayersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(allPlayers_);
        } else {
          return allPlayersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.PsichiX.JustIDS.Player all_players = 4;</code>
       *
       * <pre>
       * Only if type = GAME_INFO
       * </pre>
       */
      public int getAllPlayersCount() {
        if (allPlayersBuilder_ == null) {
          return allPlayers_.size();
        } else {
          return allPlayersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.PsichiX.JustIDS.Player all_players = 4;</code>
       *
       * <pre>
       * Only if type = GAME_INFO
       * </pre>
       */
      public com.PsichiX.JustIDS.message.PlayerInformation.Player getAllPlayers(int index) {
        if (allPlayersBuilder_ == null) {
          return allPlayers_.get(index);
        } else {
          return allPlayersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.PsichiX.JustIDS.Player all_players = 4;</code>
       *
       * <pre>
       * Only if type = GAME_INFO
       * </pre>
       */
      public Builder setAllPlayers(
          int index, com.PsichiX.JustIDS.message.PlayerInformation.Player value) {
        if (allPlayersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllPlayersIsMutable();
          allPlayers_.set(index, value);
          onChanged();
        } else {
          allPlayersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.PsichiX.JustIDS.Player all_players = 4;</code>
       *
       * <pre>
       * Only if type = GAME_INFO
       * </pre>
       */
      public Builder setAllPlayers(
          int index, com.PsichiX.JustIDS.message.PlayerInformation.Player.Builder builderForValue) {
        if (allPlayersBuilder_ == null) {
          ensureAllPlayersIsMutable();
          allPlayers_.set(index, builderForValue.build());
          onChanged();
        } else {
          allPlayersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.PsichiX.JustIDS.Player all_players = 4;</code>
       *
       * <pre>
       * Only if type = GAME_INFO
       * </pre>
       */
      public Builder addAllPlayers(com.PsichiX.JustIDS.message.PlayerInformation.Player value) {
        if (allPlayersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllPlayersIsMutable();
          allPlayers_.add(value);
          onChanged();
        } else {
          allPlayersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.PsichiX.JustIDS.Player all_players = 4;</code>
       *
       * <pre>
       * Only if type = GAME_INFO
       * </pre>
       */
      public Builder addAllPlayers(
          int index, com.PsichiX.JustIDS.message.PlayerInformation.Player value) {
        if (allPlayersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllPlayersIsMutable();
          allPlayers_.add(index, value);
          onChanged();
        } else {
          allPlayersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.PsichiX.JustIDS.Player all_players = 4;</code>
       *
       * <pre>
       * Only if type = GAME_INFO
       * </pre>
       */
      public Builder addAllPlayers(
          com.PsichiX.JustIDS.message.PlayerInformation.Player.Builder builderForValue) {
        if (allPlayersBuilder_ == null) {
          ensureAllPlayersIsMutable();
          allPlayers_.add(builderForValue.build());
          onChanged();
        } else {
          allPlayersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.PsichiX.JustIDS.Player all_players = 4;</code>
       *
       * <pre>
       * Only if type = GAME_INFO
       * </pre>
       */
      public Builder addAllPlayers(
          int index, com.PsichiX.JustIDS.message.PlayerInformation.Player.Builder builderForValue) {
        if (allPlayersBuilder_ == null) {
          ensureAllPlayersIsMutable();
          allPlayers_.add(index, builderForValue.build());
          onChanged();
        } else {
          allPlayersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.PsichiX.JustIDS.Player all_players = 4;</code>
       *
       * <pre>
       * Only if type = GAME_INFO
       * </pre>
       */
      public Builder addAllAllPlayers(
          java.lang.Iterable<? extends com.PsichiX.JustIDS.message.PlayerInformation.Player> values) {
        if (allPlayersBuilder_ == null) {
          ensureAllPlayersIsMutable();
          super.addAll(values, allPlayers_);
          onChanged();
        } else {
          allPlayersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.PsichiX.JustIDS.Player all_players = 4;</code>
       *
       * <pre>
       * Only if type = GAME_INFO
       * </pre>
       */
      public Builder clearAllPlayers() {
        if (allPlayersBuilder_ == null) {
          allPlayers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          allPlayersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.PsichiX.JustIDS.Player all_players = 4;</code>
       *
       * <pre>
       * Only if type = GAME_INFO
       * </pre>
       */
      public Builder removeAllPlayers(int index) {
        if (allPlayersBuilder_ == null) {
          ensureAllPlayersIsMutable();
          allPlayers_.remove(index);
          onChanged();
        } else {
          allPlayersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.PsichiX.JustIDS.Player all_players = 4;</code>
       *
       * <pre>
       * Only if type = GAME_INFO
       * </pre>
       */
      public com.PsichiX.JustIDS.message.PlayerInformation.Player.Builder getAllPlayersBuilder(
          int index) {
        return getAllPlayersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.PsichiX.JustIDS.Player all_players = 4;</code>
       *
       * <pre>
       * Only if type = GAME_INFO
       * </pre>
       */
      public com.PsichiX.JustIDS.message.PlayerInformation.PlayerOrBuilder getAllPlayersOrBuilder(
          int index) {
        if (allPlayersBuilder_ == null) {
          return allPlayers_.get(index);  } else {
          return allPlayersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.PsichiX.JustIDS.Player all_players = 4;</code>
       *
       * <pre>
       * Only if type = GAME_INFO
       * </pre>
       */
      public java.util.List<? extends com.PsichiX.JustIDS.message.PlayerInformation.PlayerOrBuilder> 
           getAllPlayersOrBuilderList() {
        if (allPlayersBuilder_ != null) {
          return allPlayersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(allPlayers_);
        }
      }
      /**
       * <code>repeated .com.PsichiX.JustIDS.Player all_players = 4;</code>
       *
       * <pre>
       * Only if type = GAME_INFO
       * </pre>
       */
      public com.PsichiX.JustIDS.message.PlayerInformation.Player.Builder addAllPlayersBuilder() {
        return getAllPlayersFieldBuilder().addBuilder(
            com.PsichiX.JustIDS.message.PlayerInformation.Player.getDefaultInstance());
      }
      /**
       * <code>repeated .com.PsichiX.JustIDS.Player all_players = 4;</code>
       *
       * <pre>
       * Only if type = GAME_INFO
       * </pre>
       */
      public com.PsichiX.JustIDS.message.PlayerInformation.Player.Builder addAllPlayersBuilder(
          int index) {
        return getAllPlayersFieldBuilder().addBuilder(
            index, com.PsichiX.JustIDS.message.PlayerInformation.Player.getDefaultInstance());
      }
      /**
       * <code>repeated .com.PsichiX.JustIDS.Player all_players = 4;</code>
       *
       * <pre>
       * Only if type = GAME_INFO
       * </pre>
       */
      public java.util.List<com.PsichiX.JustIDS.message.PlayerInformation.Player.Builder> 
           getAllPlayersBuilderList() {
        return getAllPlayersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.PsichiX.JustIDS.message.PlayerInformation.Player, com.PsichiX.JustIDS.message.PlayerInformation.Player.Builder, com.PsichiX.JustIDS.message.PlayerInformation.PlayerOrBuilder> 
          getAllPlayersFieldBuilder() {
        if (allPlayersBuilder_ == null) {
          allPlayersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.PsichiX.JustIDS.message.PlayerInformation.Player, com.PsichiX.JustIDS.message.PlayerInformation.Player.Builder, com.PsichiX.JustIDS.message.PlayerInformation.PlayerOrBuilder>(
                  allPlayers_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          allPlayers_ = null;
        }
        return allPlayersBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.PsichiX.JustIDS.PlayerBroadcastInfo)
    }

    static {
      defaultInstance = new PlayerBroadcastInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.PsichiX.JustIDS.PlayerBroadcastInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_PsichiX_JustIDS_Player_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_PsichiX_JustIDS_Player_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_PsichiX_JustIDS_PlayerBroadcastInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_PsichiX_JustIDS_PlayerBroadcastInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,com/PsichiX/JustIDS/message/playerInfo" +
      ".proto\022\023com.PsichiX.JustIDS\"|\n\006Player\022\n\n" +
      "\002id\030\001 \002(\t\022\014\n\004name\030\002 \002(\t\022\023\n\013life_points\030\003" +
      " \002(\001\022\022\n\nip_address\030\004 \001(\t\022/\n\005state\030\006 \002(\0162" +
      " .com.PsichiX.JustIDS.PlayerState\"\376\001\n\023Pl" +
      "ayerBroadcastInfo\022D\n\004type\030\001 \002(\01626.com.Ps" +
      "ichiX.JustIDS.PlayerBroadcastInfo.Broadc" +
      "astType\022.\n\tmy_player\030\002 \002(\0132\033.com.PsichiX" +
      ".JustIDS.Player\022\027\n\017attack_strength\030\003 \001(\001" +
      "\0220\n\013all_players\030\004 \003(\0132\033.com.PsichiX.Just",
      "IDS.Player\"&\n\rBroadcastType\022\t\n\005STATE\020\000\022\n" +
      "\n\006ATTACK\020\001*h\n\013PlayerState\022\013\n\007WAITING\020\000\022\013" +
      "\n\007IN_GAME\020\001\022\013\n\007PLAYING\020\002\022\014\n\010OBSERVER\020\003\022\007" +
      "\n\003WON\020\004\022\010\n\004LOST\020\005\022\021\n\rGAME_FINISHED\020\006B0\n\033" +
      "com.PsichiX.JustIDS.messageB\021PlayerInfor" +
      "mation"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_PsichiX_JustIDS_Player_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_PsichiX_JustIDS_Player_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_PsichiX_JustIDS_Player_descriptor,
              new java.lang.String[] { "Id", "Name", "LifePoints", "IpAddress", "State", });
          internal_static_com_PsichiX_JustIDS_PlayerBroadcastInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_PsichiX_JustIDS_PlayerBroadcastInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_PsichiX_JustIDS_PlayerBroadcastInfo_descriptor,
              new java.lang.String[] { "Type", "MyPlayer", "AttackStrength", "AllPlayers", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
